server:
  port: ${PORT:9999}
  servlet:
    context-path: /branium-academy

spring:
  application:
    name: be-branium-academy

  datasource:
    url: jdbc:mysql://localhost:3306/branium_academy
    username: root
    password: Sohappy212@

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect