server:
  port: ${PORT:8080}
  servlet:
    context-path: /branium-academy/api/v1
spring:
  application:
    name: be-branium-academy
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: han_branium_academy
    password: Sohappy212
  jpa:
    database: oracle
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
logging:
  level:
   org.springframework.security: trace
